<?php
namespace Mare\Controller;
use Think\Controller;
use Think\Page;

class CommonController extends Controller {
    protected $tid;
    protected $userid;
    protected $url;
    protected $showaction;
    
	public function __construct() {
        parent::__construct();
//         openlog ( "webactionLog" ,  LOG_PID  |  LOG_PERROR ,  LOG_LOCAL0 );
//         syslog(LOG_INFO,
//             "This is a syslog test message generated by program '%s'\n");
//         closelog();

        
        //print_r($_SESSION);
        $setmode = getSetMode();
        
        
        //判断用户的session是否为空，是的话就跳转至登录界面
        if($_SESSION[$_SESSION['randomstr']]['userid'] == null){
            $this->redirect('Mare/Login/login_user');
        }
        
        /******2017/12/6对已有用户进行角色变更时，系统提示变更成功，但刷新后并未变更*******/
        $res = D("User")->field('userid,tid,loginemail,check_status,status,realname as nickname,at_usertype.name as authname,lockstarttime')
            ->where(array('userid'=>$_SESSION[$_SESSION['randomstr']]['userid']))
            ->join('left join at_userauth on at_userauth.uid = at_user.userid')
            ->join('left join at_usertype on at_usertype.id = at_userauth.tid')
            ->find();
        if ($res) {
            if ($res['tid'] == 1) {
                session('randomstr',null);
                $this->redirect('Mare/Login/login_user');
            }
            if ($res['tid'] != $_SESSION[$_SESSION['randomstr']]['tid']) {
                session('randomstr',null);
                $randomstr 	= createRand(32);
                session('randomstr',$randomstr);
                session($randomstr,$res);
            }
        } else {
            session('randomstr',null);
            $this->redirect('Mare/Login/login_user');
        }
        /******2017/12/6对已有用户进行角色变更时，系统提示变更成功，但刷新后并未变更*******/
        
        //判断是否有版本控制这个session值
    	$licinfo 	= D('Licinfo');
        $device     = D('device');
        $devicelist = $device->field('devtask,devid')->select();
        foreach ($devicelist as $key => $value) {
            if( !is_null($value['devtask']) && time() - $value['devtask'] > 259200 ){
//                 echo time() - $value['devtask'];die();
                @$device->where(array('devid'=>$value['devid']))->delete();
            }
        }
		$systeminfo = $licinfo->find(1);
		if($systeminfo){
			$_SESSION[$_SESSION['randomstr']]['showaction']	= $systeminfo['showaction'];
		}else{
			$_SESSION[$_SESSION['randomstr']]['showaction']	= "111"; 
		}
		
		$this->tid = $_SESSION[$_SESSION['randomstr']]['tid'];
		$this->userid = $_SESSION[$_SESSION['randomstr']]['userid'];
		$this->url = MODULE_NAME.'/'.CONTROLLER_NAME.'/'.ACTION_NAME;
		$this->showaction = $_SESSION[$_SESSION['randomstr']]['showaction'];
    }
    
    /**
     * 分页查询
     * @param unknown $model_view 模型
     * @param unknown $where 查询条件
     * @param string $order 排序
     * @param string $group 分组查询
     * @return 返回查询结果
     * @author qxn
     */
    protected function Tpage($model_view, $where, $order = "",$group = "")
    {
        $page_size = 12;
        $p         = isset($_GET['p']) ? intval($_GET['p']) : 1;
        $star      = ($p-1)*$page_size;
        if ($_POST) {
            $list = $model_view->where($where)->order($order)->select();
        } else {
            $list = $model_view->where($where)->order($order)->group($group)->page($p . ',' . $page_size)->select();
            if($group == ''){
                $count = $model_view->where($where)->count();
            }else{
                $count = count($model_view->where($where)->group($group)->order($order)->select());
            }
            $Page = new Page($count, $page_size);
            $Page->setConfig('header', '<br/><li class="rows">共<b>%TOTAL_ROW%</b>条记录  每页<b>' .
                $count. '</b>条  第<b>%NOW_PAGE%</b>页/共<b>%TOTAL_PAGE%</b>页</li>');
            $Page->setConfig('prev', '上一页');
            $Page->setConfig('last', '末页');
            $Page->setConfig('first', '首页');
            $Page->setConfig('next', '下一页');
            $Page->setConfig('theme', '%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
            $show = $Page->show();
            $this->assign('star', $star);
            $this->assign('pageshow', $show);
        }
        return $list;
    }
    
    
    /**
     * 记录日子
     * @param unknown $content
     * @param unknown $result
     * @param unknown $remarks
     * @author
     */
    protected function do_log($content, $result, $remarks) {
        @addMareLog(array(
            'username'      => get_user_info()['realname'],
            'handleurl'     => $this->url,
            'handlecontent' => $content,
            'handleresult'  => $remarks,
            'handleremarks' => $remarks
        ));
    }
}
